#%RAML 1.0 DataType
type: object
description: Starship details that satisfy the requested mission.
properties:
  name:
    type: string
    required: true
    description: Name of the starship.
    example:  Millennium Falcon
  model:
    type: string
    required: true
    description: Manufacturer model of the starship.
    example: YT-1300 light freighter
  starshipClass:
    type: string
    required: true
    description: Classification of the starship.
    example: Light freighter

  maxCargoWeight:
    type: integer
    required: false
    description: Maximum cargo capacity in kilograms.
    example: 100000

  maxCrew:
    type: string
    required: true
    description: Maximum crew supported by the starship.
    example: "4"

  maxPassengers:
    type: integer
    required: true
    description: Maximum passenger capacity.
    example: 6
  hyperdriveRating:
    type: integer
    required: true
    description: hyperdrive rating value
    example: 2
      
    
    
      