#%RAML 1.0 NamedExample
{
  "missionSupported": true,
  "message": "2 starship(s) satisfy the mission requirements.",
  "matchingShips": [
    {
      "name": "Millennium Falcon",
      "model": "YT-1300 light freighter",
      "starshipClass": "Light freighter",
      "cargoCapacity": 100000,
      "crew": 4,
      "passengers": 6
    },
    {
      "name": "Imperial Shuttle",
      "model": "Lambda-class T-4a shuttle",
      "starshipClass": "Armed government transport",
      "cargoCapacity": 80000,
      "crew": 6,
      "passengers": 20
    }
  ]
}