#%RAML 1.0 NamedExample
{
  "missionSupported": true,
  "message": "2 starship(s) satisfy the mission requirements.",
  "matchingShips": [
    {
      "name": "Millennium Falcon",
      "model": "YT-1300 light freighter",
      "starshipClass": "Light freighter",
      "maxCargoWeight": 100000,
      "maxCrew": "4",
      "maxPassengers": 6,
      "hyperdriveRating":4
    },
    {
      "name": "Imperial Shuttle",
      "model": "Lambda-class T-4a shuttle",
      "starshipClass": "Armed government transport",
      "maxCargoWeight": 80000,
      "maxCrew": "6",
      "maxPassengers": 20,
      "hyperdriveRating":2
    }
  ]
}